# Generated by Django 2.0 on 2020-05-11 13:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tagline',
            field=models.CharField(max_length=100),
        ),
    ]
