# Generated by Django 2.0 on 2020-05-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_newtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTable',
        ),
    ]
