# Generated by Django 2.0 on 2020-05-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_delete_newtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_image', verbose_name='Add Photo or Article'),
        ),
    ]
