# Generated by Django 2.0 on 2020-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200516_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personal_image'),
        ),
    ]
