# Generated by Django 2.0 on 2020-05-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_personal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='git',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='slack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
